### PR TITLE
Added installation hints for Python packages

### PR DESCRIPTION
**Pull request by HolQue**
Reference: https://github.com/test-fullautomation/robotframework-documentation/issues/41

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Holger,
looks good to me!
Is it possible to add to the Bosch-Internal release a chapter which includes the proxy name? I would like to have a copy&paste solution.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

currently this is a generic solution. I have to divide this in two different parts. Not nice - but possible. Available soon.

**Comment by test-fullautomation** [comment]
Hi Holger,
very good!
This is a very common question how to extend the python. Even we have to see that this is immediately visible somewhere at the beginning of the documentation.
Most people think this is not possible, what is very bad.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Done with
https://github.com/test-fullautomation/robotframework-documentation/pull/44

**Pull request merged**
