### PR TITLE
Configuration file and main TEX file divided

### PR DESCRIPTION
**Pull request by HolQue**
into OSS version and BIOS version.

* Configuration files (with documentation inside):
  - maindoc/maindoc_configs/maindoc_config_BIOS.json
  - maindoc/maindoc_configs/maindoc_config_OSS.json
* Main TEX files:
  - book/RobotFrameworkAIO_Reference_BIOS.tex
  - book/RobotFrameworkAIO_Reference_OSS.tex

Command line parameter --configfile mandatory now

### CODE REVIEW

**Comment by HolQue** [comment]
Solves https://github.com/test-fullautomation/robotframework-documentation/issues/24

**Comment by HolQue** [comment]
Solves also
https://github.com/test-fullautomation/robotframework-documentation/issues/25

**Comment by HolQue** [comment]
Seems that https://github.com/test-fullautomation/robotframework-documentation/pull/23 is lost.

I will check.

Please wait with integration of this pull request.

**Comment by HolQue** [comment]
Done now. Pull request ready for integration.

**Review by test-fullautomation — APPROVED** [review]
Hi Holger,

very good! Next problem solved...

Thank you,
 Thomas

**Pull request merged**
