### PR TITLE
Describe workflow how to integrate a new repository

### PR DESCRIPTION
**Pull request by huavanthong**
Hi Thomas,

I have updated the document for this ticket https://github.com/test-fullautomation/RobotFramework_AIO/issues/291
Please help me review it.

Thank you and best regards,
Thong Hua

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Thong,

I recommend slightly rephrasing some of the content.

This is not a helpful headline:

`"For RobotFramework AIO developer"`

Alternative:

`"Adding new components"`

The first two sentences

```
This subchapter will guide developers integrate a new components into RobotFramework AIO.
To integrate a new component into the RobotFramework AIO project on GitHub, follow these steps:
```

can be shortened. Alternative:

`To add a new component to the RobotFramework AIO project on GitHub, follow these steps:`

Tiny typo:

Not: `Create a New Repository:`
But: `Create a new Repository:`

**Comment by huavanthong** [comment]
Hi Holger,

Thank you for your comments. I have updated it.

Best regards,
Thong Hua

**Review by HolQue — COMMENTED** [review]
Fine to me now!

Thank you.

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
thank you for your pull-request!
I have to apologize. After rethinking I came to the conclusion that  this should be **not** part of the main documentation. 
Therefore I will not merge the pull-request.
The purpose of the main documentation is to support users of RobotFramework AIO.

The content is a very good starting point.
Please create a `PROCESSES.md` file in the root of RobotFramework_AIO repo with the same content.
Headline is "Add new repository to RobotFramework AIO".
Please also add the location of all files to your documentation.

Thank you,
 Thomas

**Pull request closed without merging**
